# action.yml
name: "Prestashop PHP 7.2 Linter"
description: "PHP linter for 7.2"
inputs:
  folder-to-exclude:
    description: "Folder to exclude"
    required: false
    default: '! -path "./vendor/*"'
  working-directory:
    description: "Working directory"
    required: false
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.working-directory }}
    - ${{ inputs.folder-to-exclude }}
